# This is a basic workflow to help you get started with Actions

name: build and publish

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    tags: [ "v*" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: 'alpine:3.12'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - run: |
          apk add --no-cache \
              curl \
              gcc \
              g++ \
              gmp-dev \
              ncurses-dev \
              libffi-dev \
              zlib-dev \
              make \
              xz \
              tar \
              perl \
              bash \
              shadow \
              openssh-client \
              binutils-gold \
              zlib-static \
              ncurses-static \
              sudo
      - uses: haskell/actions/setup@v2
        id: setup-haskell-cabal
        name: Setup Haskell
        with:
          ghc-version: '9.4'
          cabal-version: '3.6'

      - uses: actions/cache@v3
        name: Cache cabal-store
        with:
          path: ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
          key: cabal-r1

      - run: |
          cabal install weeder -j \
            --constraint weeder==2.5.0 \
            --enable-executable-static --enable-static \
            --enable-relocatable --enable-split-sections \
            --enable-executable-stripping --disable-shared \
            --ghc-options='-fPIC -fasm -optl-static -optl-pthread +RTS -A64m -RTS' \
            --install-method=copy \
            --installdir=.

      - name: Check executable runs
        run: ./weeder --version

      - name: Check that executable is static
        run: |
          ldd ./weeder 2>&1 || true
          ldd ./weeder 2>&1 | grep -q 'Not a valid dynamic program'

      - uses: actions/upload-artifact@v3
        with:
          name: weeder
          path: weeder

  release:
    permissions:
      contents: write
    needs: [build]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
    - run: ls -R
    - run: gzip weeder/weeder
    - name: Create release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        hub release create \
          --attach weeder/weeder.gz \
          --message "${{ github.ref_name }}" \
          ${{ github.ref_name }}
